export const ErrorCodes = Object.freeze({
  UNKNOWN_ERROR: 'E000',
  VALIDATION_ERROR: 'E001',
  AUTHENTICATION_FAILED: 'E002',
  AUTHORIZATION_FAILED: 'E003',
  NOT_FOUND: 'E004',
  CONFLICT: 'E005',
  BAD_REQUEST: 'E006',
  TIMEOUT: 'E007',
  SERVICE_UNAVAILABLE: 'E008'
});
